permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: sixgod
  email: yf6101008@163.COM
  link: https://github.com/iamsixer
  github: https://github.com/iamsixer

# 站点信息
title: sixgod的博客
description: sixgod的博客
url: https://github.com/iamsixer
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/5754179?v=3&s=460
favicon: http://7xid3r.com1.z0.glb.clouddn.com/my16.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
#disqus:
#  shortname: sixgod
